version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: pg_image_upload
    environment:
      POSTGRES_DB: image_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
