spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/image_db
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
